# Generated by Django 3.0.4 on 2020-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('ecorregion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=50)),
                ('nombrecomun', models.CharField(max_length=50)),
                ('baseregistro', models.TextField()),
                ('identificador', models.CharField(max_length=50)),
                ('añoidentificacion', models.DateField()),
                ('departamento', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('localidad', models.CharField(max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('autor', models.CharField(max_length=20)),
                ('fechacaptura', models.DateField()),
                ('ecorregion', models.ManyToManyField(to='ecorregion.Ecorregion')),
                ('proyecto', models.ManyToManyField(to='proyecto.Proyecto')),
            ],
        ),
    ]
