# Generated by Django 3.0.4 on 2020-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='añoidentificacion',
            field=models.CharField(max_length=50),
        ),
    ]
