# Generated by Django 3.0.4 on 2020-07-16 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('ecorregion', '0001_initial'),
        ('registro', '0002_auto_20200715_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='ecorregion',
        ),
        migrations.AddField(
            model_name='registro',
            name='ecorregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecorregion.Ecorregion'),
        ),
        migrations.RemoveField(
            model_name='registro',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='registro',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto'),
        ),
    ]
